import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SubNavbar from "../components/SubNavbar";
import MainNavbar from "../components/MainNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HotelsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
      <SubNavbar />
    </>
  );
}
